In [2]:
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer

X = np.array([[10], [15], [20], [25], [30], [35], [40], [45]])

### Equal-Width Discretization


In [3]:
ew = KBinsDiscretizer(
    n_bins=3,
    encode="ordinal",
    strategy="uniform"   # equal-width
)

X_ew = ew.fit_transform(X)
X_ew

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.]])

### Equal-Frequency Discretization


In [4]:
ef = KBinsDiscretizer(
    n_bins=3,
    encode="ordinal",
    strategy="quantile"  # equal-frequency
)

X_ef = ef.fit_transform(X)
X_ef

/opt/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(


array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.]])

### Arbitrary Discretization (Manual Bins)


In [5]:
bins = [0, 20, 35, 50]  # domain-driven cut points
X_arbitrary = np.digitize(X.flatten(), bins)

X_arbitrary


array([1, 1, 2, 2, 2, 3, 3, 3])

### Discretization Using K-Means


In [ ]:
km = KBinsDiscretizer(
    n_bins=3,
    encode="ordinal",
    strategy="kmeans"
)

X_km = km.fit_transform(X)
X_km

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.]])

### Discretization Using Decision Tree


In [7]:
from sklearn.tree import DecisionTreeClassifier

y = np.array([0, 0, 0, 1, 1, 1, 1, 1])

dt = DecisionTreeClassifier(max_depth=2)
dt.fit(X, y)

thresholds = dt.tree_.threshold
thresholds = thresholds[thresholds != -2]  # valid splits

print("Split thresholds:", thresholds)


Split thresholds: [22.5]


### Binarization


In [9]:
from sklearn.preprocessing import Binarizer

binz = Binarizer(threshold=30)
X_bin = binz.fit_transform(X)

X_bin

array([[0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])